require 'rubygems'
require 'rake'
require 'rake/extensiontask'

Rake::ExtensionTask.new do |extension|
  extension.name    = 'relation_table'
  extension.ext_dir = 'ext/ruby_relation/relation_table'
  extension.lib_dir = 'lib/relation'
end

task :clean_and_clobber_without_verbose do
  verbose(false)
  Rake::Task["clean"].invoke
  Rake::Task["clobber"].invoke
  puts "\nClean and Clobber ok \n"
end